name: OrangeOre
main: com.soldin.orangeore.OrangeOrePlugin
version: 1.1
api-version: 1.16
commands:
  orangenew:
    description: Управление новой рудой
    usage: /orangenew <give|reload>
    aliases: [oor]
  soldinsera:
    description: Респавн залежей руды
    usage: /soldinsera respawn
